# Generated by Django 3.2.7 on 2021-10-08 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(default='SOME STRING', max_length=30)),
                ('departmentLocation', models.CharField(default='SOME STRING', max_length=30)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(default='SOME STRING', max_length=30)),
                ('creationDate', models.DateField()),
                ('projectOwner', models.CharField(default='SOME STRING', max_length=30)),
                ('projectDescription', models.CharField(default='SOME STRING', max_length=30)),
                ('employee', models.ManyToManyField(to='todo.Employee')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
    ]
