# Generated by Django 3.2.7 on 2021-10-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_department_employee_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_date',
            new_name='taskDueDate',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='employee',
            field=models.ManyToManyField(to='todo.Employee'),
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
        migrations.AddField(
            model_name='todo',
            name='taskComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='taskDescription',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='todo',
            name='taskName',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='todo',
            name='taskPriority',
            field=models.SmallIntegerField(
                choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], default=0),
        ),
        migrations.AlterModelTable(
            name='todo',
            table='Todo',
        ),
    ]
