# Generated by Django 3.2.7 on 2021-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20211008_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='employee',
            field=models.ManyToManyField(to='todo.Employee', verbose_name='todo_employee'),
        ),
    ]
