# Generated by Django 3.2.7 on 2021-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='employee',
            field=models.ManyToManyField(to='todo.Employee'),
        ),
    ]
