# Generated by Django 3.2.7 on 2021-10-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(default='2021-10-11'),
        ),
    ]
