# Generated by Django 3.2.7 on 2021-10-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_project_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='taskCreate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taskcreate', to='todo.employee'),
        ),
    ]
