# Generated by Django 3.2.7 on 2021-10-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_taskcreate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectOwner',
        ),
    ]
