# Generated by Django 3.2.7 on 2021-10-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_project_projectowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectCreate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectcreate', to='todo.employee'),
        ),
    ]
