# Generated by Django 3.2.7 on 2021-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_project_projectcreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
    ]
