# Generated by Django 3.2.7 on 2021-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_project_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentLocation',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='taskDescription',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='taskName',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
