# Generated by Django 3.2.7 on 2021-10-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20211014_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='employee',
        ),
        migrations.AddField(
            model_name='todo',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.employee'),
        ),
    ]
