# Generated by Django 3.2.7 on 2021-10-15 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0012_auto_20211014_1815'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='project',
        #     name='employee',
        #     field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='projectCreate',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectcreate', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='todo',
        #     name='employee',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='todo',
        #     name='taskCreate',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taskcreate', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.DeleteModel(
        #     name='Employee',
        # ),
    ]
