# Generated by Django 3.2.7 on 2021-10-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20211015_0454'),
        ('todo', '0013_auto_20211015_1146'),
    ]

    operations = [
    ]
