# Generated by Django 3.2.7 on 2021-10-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_merge_0013_auto_20211015_0454_0013_auto_20211015_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(default='', max_length=500),
        ),
    ]
