# Generated by Django 3.2.7 on 2021-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_project_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
