# Generated by Django 3.2.7 on 2021-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20211020_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='taskDescription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='taskName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
