# Generated by Django 3.2.7 on 2021-10-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20211020_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creationDate',
            new_name='startDate',
        ),
    ]
