# Generated by Django 3.2.7 on 2021-11-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/'),
        ),
    ]
